name: Documentation
description: Suggest improvements to documentation
labels: ["documentation"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve our documentation!

  - type: input
    id: title
    attributes:
      label: Documentation Title
      description: What documentation needs improvement?
      placeholder: "API documentation: Missing examples for authentication endpoints"
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Issue with Current Documentation
      description: What is missing, unclear, or incorrect?
      placeholder: The authentication API section does not include curl examples...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: Add curl examples for each endpoint, include sample responses...
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is this documentation located?
      placeholder: docs/API_DOCUMENTATION.md or README.md
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Documentation Type
      options:
        - Setup/Installation Guide
        - API Reference
        - Architecture Guide
        - Contributing Guide
        - Troubleshooting
        - Examples/Tutorials
        - Code Comments
        - Other
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked existing documentation
          required: true
        - label: This is not a duplicate
          required: true
