# Generated by Django 4.2.27 on 2025-12-13 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['level', 'name']},
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('DIP', 'Diploma'), ('CERT', 'Certificate'), ('DEG', 'Bachelor Degree'), ('MASTER', 'Master Degree'), ('PHD', 'Doctor of Philosophy')], default='DEG', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reg_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Format must be T/XXXX/YYYY/NNNN (e.g., T/DEG/2025/001)', regex='^T/(DEG|CERT|DIP|MASTER|PHD)/\\d{4}/\\d{3,4}$')], verbose_name='Registration Number'),
        ),
    ]
