# Generated by Django 4.2.27 on 2025-12-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_course_options_course_level_alter_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='surname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Surname'),
        ),
    ]
