# Generated by Django 4.2.27 on 2025-12-11 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=15000.0, max_digits=10, verbose_name='Amount (TZS)')),
                ('provider', models.CharField(choices=[('mpesa', 'M-Pesa'), ('stripe', 'Stripe'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], default='mpesa', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Transaction ID from Provider')),
                ('reference_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Member Reference Code')),
                ('payment_method_details', models.JSONField(blank=True, default=dict, help_text='Additional payment method details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membership Payment',
                'verbose_name_plural': 'Membership Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('event_type', models.CharField(max_length=50)),
                ('raw_data', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='membership.membershippayment')),
            ],
            options={
                'verbose_name': 'Payment Webhook Log',
                'verbose_name_plural': 'Payment Webhook Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='membershippayment',
            index=models.Index(fields=['user', '-created_at'], name='membership__user_id_3d9468_idx'),
        ),
        migrations.AddIndex(
            model_name='membershippayment',
            index=models.Index(fields=['status', 'created_at'], name='membership__status_62513b_idx'),
        ),
    ]
